# Generated by Django 5.2.2 on 2025-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='docs/')),
                ('tags', models.CharField(max_length=500)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
